introduce -u option for command scripts

diff --git a/bin/auxcog b/bin/auxcog
--- a/bin/auxcog
+++ b/bin/auxcog
@@ -9,20 +9,19 @@ fi
 
 BIN=$GENCOT_HOME/bin
 
-USAGE="Usage: $0 [-I<dir>] [unit|comments|help] <file>"
+USAGE="Usage: $0 [-I<dir>] [-u<unam>] [unit|comments|help] [<file>]"
 
 long_usage()
 {
     echo $USAGE
     echo 'Auxiliary processing for Cogent programs.'
     echo 'Commands:'
-    echo '  unit     <ufile>  Generate auxiliary C files for unit described in <ufile>'
-    echo '  comments <file>   Remove comments from Cogent source <file> and print to stdout'
-    echo '  help              Display this help information'
-    echo 'A <ufile> contains a list of C source file names, each on a separate line.'
-    echo 'The base name of a <ufile> must be the name of the corresponding Cogent compilation unit.'
+    echo '  unit             Generate auxiliary C files for unit described in <ufile>'
+    echo '  comments <file>  Remove comments from Cogent source <file> and print to stdout'
+    echo '  help             Display this help information'
     echo 'Options for command unit: '
-    echo '  -I<dir>  Directory for searching Cogent include files. Can be repeated, as for cpp. '
+    echo '  -I<dir>    Directory for searching Cogent include files. Can be repeated, as for cpp. '
+    echo '  -u<uname>  Name of unit. Default is "all"'
 }
 
 short_usage()
@@ -32,7 +31,7 @@ short_usage()
 }
  
 # Parse options
-OPTS=$(getopt -o hI: -n "$0" -- "$@")
+OPTS=$(getopt -o hu:I: -n "$0" -- "$@")
 
 if [ $? != 0 ]
 then
@@ -43,19 +42,24 @@ fi
 eval set -- "$OPTS"
 
 INCLS=''
+UNITNAME='all'
 
 while true; do
     case "$1" in
         -h) long_usage; exit;;
         -I) shift; INCLS="$INCLS -I $1"; shift;;
+        -u) shift; UNITNAME="$1"; shift;;
         --) shift; break;;
     esac
 done
 
+# Parse command
+REQARGS=1
+OPTARGS=''
 CMD=$1
 
 case "$CMD" in
-    unit) ;;
+    unit) REQARGS=0;;
     comments) ;;
     help) long_usage; exit;;
     *) echo "unknown auxcog command: $1"; short_usage; exit;;
@@ -63,31 +67,55 @@ esac
 
 shift
 
+if [ $OPTARGS ]
+then
+    if [ $REQARGS -gt $# ]
+    then
+        echo "wrong number of arguments for auxcog subcommand ${CMD}: expected at least $REQARGS"
+        exit
+    fi
+else
+    if [ "$REQARGS" != "$#" ]
+    then
+        echo "wrong number of arguments for auxcog subcommand ${CMD}: expected $REQARGS"
+        exit
+    fi
+fi
+
+UNITFILE=$UNITNAME.unit
+
+if [ "$REQARGS" = "0" ]
+then
+    if [ -e $UNITFILE ]
+    then 
+        echo "Using unit file $UNITFILE" >&2
+    else
+        echo "Error: Unit file $UNITFILE not found."
+        exit
+    fi
+fi
+
 if [ "$CMD" = "unit" ]
 then
-    UFILE=$1
-    UBASE=$(basename $UFILE)
-    UNAME=$(expr match $UBASE '\(.*\)[.][^.]*' '|' $UBASE)
-    
-    $BIN/auxcog-macros $INCLS $UNAME.cogent \
+    $BIN/auxcog-macros $INCLS $UNITNAME.cogent \
     | $BIN/auxcog-remcomments \
-    | $BIN/auxcog-numexpr > $UNAME-macros.h
+    | $BIN/auxcog-numexpr > $UNITNAME-macros.h
     
-    if [ -e $UNAME-gencot_pp_inferred.c ]
+    if [ -e $UNITNAME-gencot_pp_inferred.c ]
     then
-        $BIN/auxcog-genops $UNAME-gen.h < $UNAME-gencot_pp_inferred.c > $UNAME-gencot.c
+        $BIN/auxcog-genops $UNITNAME-gen.h < $UNITNAME-gencot_pp_inferred.c > $UNITNAME-gencot.c
     fi
-    $BIN/auxcog-genops $UNAME-gen.h < $UNAME-externs_pp_inferred.c > $UNAME-externs.c
-    for file in $(cat $UFILE)
+    $BIN/auxcog-genops $UNITNAME-gen.h < $UNITNAME-externs_pp_inferred.c > $UNITNAME-externs.c
+    for file in $(cat $UNITFILE)
     do
         fbase=$(basename $file)
         fnam=$(expr match $fbase '\(.*\)[.][^.]*' '|' $fbase)
         if [ $fnam != "additional_externs" ]
-        then $BIN/auxcog-genops $UNAME-gen.h < $fnam-entry_pp_inferred.c > $fnam-entry.c
+        then $BIN/auxcog-genops $UNITNAME-gen.h < $fnam-entry_pp_inferred.c > $fnam-entry.c
         fi
     done
     
-    $BIN/auxcog-mainfile $UNAME < $UFILE > $UNAME.c
+    $BIN/auxcog-mainfile $UNITNAME < $UNITFILE > $UNITNAME.c
 else
 # "$CMD" = "comments"
     $BIN/auxcog-remcomments < $1
diff --git a/bin/gencot b/bin/gencot
--- a/bin/gencot
+++ b/bin/gencot
@@ -9,26 +9,26 @@ fi
 
 BIN=$GENCOT_HOME/bin
 
-USAGE="Usage: $0 [-I<dir>] [-G<dir>] [-C<dir>] [-k] [check|config|hfile|cfile|unit|cgraph|help] <file>"
+USAGE="Usage: $0 [-I<dir>] [-G<dir>] [-C<dir>] [-u<uname>] [-k] [check|config|hfile|cfile|unit|cgraph|help] [<file>]"
 
 long_usage()
 {
     echo $USAGE
     echo 'Translate C source files to Cogent language.'
     echo 'Subcommands:'
-    echo '  check  <cfile>  Test C sourcefile <cfile> for parsability by Gencot'
+    echo '  check  <file>   Test C sourcefile <file> for parsability by Gencot'
     echo '  config <hfile>  Translate a C configuration include file to Cogent'
     echo '  hfile  <hfile>  Translate a C include file to Cogent'
     echo '  cfile  <cfile>  Translate a C source file to Cogent'
-    echo '  unit   <ufile>  Generate auxiliary Cogent files for unit described in <ufile>'
-    echo '  cgraph <ufile>  Print call graph for unit described in <ufile>'
+    echo '  unit            Generate auxiliary Cogent files for unit'
+    echo '  cgraph          Print call graph for unit'
     echo '  help            Display this help information'
-    echo 'A <ufile> contains a list of <cfile> names, each on a separate line.'
     echo 'Options: '
-    echo '  -I<dir>  Directory for searching C include files. Can be repeated, as for cpp. '
-    echo '  -G<dir>  Directory for searching Gencot auxiliary files. Only one can be given, default is "."'
-    echo '  -C<dir>  Directory for stored declaration comments. Default is "./comments"'
-    echo '  -k   Keep directory with intermediate files and display it at the end.'
+    echo '  -I<dir>    Directory for searching C include files. Can be repeated, as for cpp. '
+    echo '  -G<dir>    Directory for searching Gencot auxiliary files. Only one can be given, default is "."'
+    echo '  -C<dir>    Directory for stored declaration comments. Default is "./comments"'
+    echo '  -u<uname>  Name of unit. Default is "all"'
+    echo '  -k         Keep directory with intermediate files and display it at the end.'
 }
 
 short_usage()
@@ -38,7 +38,7 @@ short_usage()
 }
 
 # Parse options
-OPTS=$(getopt -o hkI:G:C: -n "$0" -- "$@")
+OPTS=$(getopt -o hku:I:G:C: -n "$0" -- "$@")
 
 if [ $? != 0 ]
 then
@@ -52,6 +52,8 @@ INCLPATH=''
 GENCOTDIR='.'
 COMMENTDIR='./comments'
 KEEP=''
+UNITNAME='all'
+
 add_incl()
 {
     if [ "$1" = "." ] 
@@ -70,6 +72,7 @@ while true; do
     case "$1" in
         -h) long_usage; exit;;
         -k) KEEP='yes'; shift;;
+        -u) shift; UNITNAME="$1"; shift;;
         -I) shift; add_incl "$1"; shift;;
         -G) shift; GENCOTDIR="$1"; shift;;
         -C) shift; COMMENTDIR="$1"; shift;;
@@ -79,16 +82,16 @@ done
 
 # Parse command
 REQARGS=1
-OPTARGS='yes'
+OPTARGS=''
 CMD=$1
 
 case "$CMD" in
-    check) OPTARGS='';;
+    check) ;;
     config) ;;
     hfile) ;;
     cfile) ;;
-    unit) ;;
-    cgraph) ;;
+    unit) REQARGS=0;;
+    cgraph) REQARGS=0;;
     help) long_usage; exit;;
     *) echo "unknown gencot subcommand: $1"; short_usage; exit;;
 esac
@@ -110,11 +113,24 @@ else
     fi
 fi
 
-CFILE=$1
-CBASE=$(basename $CFILE)
-CNAME=$(expr match $CBASE '\(.*\)[.][^.]*' '|' $CBASE)
+UNITFILE=$UNITNAME.unit
 
-IPMFILE=$CBASE-itemprops
+if [ $REQARGS -gt 0 ]
+then
+    CFILE=$1
+    CBASE=$(basename $CFILE)
+    CNAME=$(expr match $CBASE '\(.*\)[.][^.]*' '|' $CBASE)
+    IPMFILE=$CBASE-itemprops
+else
+    IPMFILE=$UNITFILE-itemprops
+    if [ -e $GENCOTDIR/$UNITFILE ]
+    then 
+        echo "Using unit file $UNITFILE" >&2
+    else
+        echo "Error: Unit file $UNITFILE not found."
+        exit
+    fi
+fi
 
 TMPDIR=$(mktemp -d)
 
@@ -223,12 +239,12 @@ process_comments()
 
 if [ "$CMD" = "unit" ]
 then
-    for file in $(cat $CFILE)
+    for file in $(cat $GENCOTDIR/$UNITFILE)
     do prepare_cfile $file
     done
-    MIFILE=$GENCOTDIR/$CNAME.unit-manitems
-    PMIFILE=$TMPDIR/$CNAME.unit-prcmanitems
-    EIFILE=$TMPDIR/$CNAME.unit-extitems
+    MIFILE=$GENCOTDIR/$UNITFILE-manitems
+    PMIFILE=$TMPDIR/$UNITFILE-prcmanitems
+    EIFILE=$TMPDIR/$UNITFILE-extitems
     if [ -e $MIFILE ]
     then
         $BIN/gencot-prclist < $MIFILE > $PMIFILE
@@ -238,21 +254,21 @@ then
     $BIN/items-used $PMIFILE < $TMPDIR/infiles > $EIFILE
     prepare_itemprops
     $BIN/gencot-externs $TMPDIR/$IPMFILE $EIFILE < $TMPDIR/infiles | $BIN/gencot-reporigs \
-        | $BIN/gencot-mrgcomments /dev/null > $TMPDIR/$CNAME-externs.cogent
+        | $BIN/gencot-mrgcomments /dev/null > $TMPDIR/$UNITNAME-externs.cogent
     $BIN/gencot-exttypes $TMPDIR/$IPMFILE $EIFILE < $TMPDIR/infiles | $BIN/gencot-reporigs \
         | $BIN/gencot-defcomments $COMMENTDIR \
-        | $BIN/gencot-mrgcomments /dev/null > $TMPDIR/$CNAME-exttypes.cogent
+        | $BIN/gencot-mrgcomments /dev/null > $TMPDIR/$UNITNAME-exttypes.cogent
     $BIN/gencot-dvdtypes $TMPDIR/$IPMFILE $EIFILE < $TMPDIR/infiles | $BIN/gencot-reporigs \
         | $BIN/gencot-defcomments $COMMENTDIR \
-        | $BIN/gencot-mrgcomments /dev/null > $TMPDIR/$CNAME-dvdtypes.cogent
-    cp $TMPDIR/$CNAME-externs.cogent $TMPDIR/$CNAME-exttypes.cogent $TMPDIR/$CNAME-dvdtypes.cogent .
-    $BIN/gencot-mainfile $CNAME < $CFILE > $CNAME.cogent
+        | $BIN/gencot-mrgcomments /dev/null > $TMPDIR/$UNITNAME-dvdtypes.cogent
+    cp $TMPDIR/$UNITNAME-externs.cogent $TMPDIR/$UNITNAME-exttypes.cogent $TMPDIR/$UNITNAME-dvdtypes.cogent .
+    $BIN/gencot-mainfile $UNITNAME < $GENCOTDIR/$UNITFILE > $UNITNAME.cogent
 elif [ "$CMD" = "cgraph" ]
 then
-    for file in $(cat $CFILE)
+    for file in $(cat $GENCOTDIR/$UNITFILE)
     do prepare_cfile $file
     done
-    $BIN/callgraph-print $CFILE < $TMPDIR/infiles
+    $BIN/callgraph-print $GENCOTDIR/$UNITFILE < $TMPDIR/infiles
 elif [ "$CMD" = "check" ]
 then 
     prepare_cfile $CFILE
diff --git a/bin/items b/bin/items
--- a/bin/items
+++ b/bin/items
@@ -11,26 +11,26 @@ BIN=$GENCOT_HOME/bin
 PRC=$BIN/items-proc
 GEN=$BIN/items-gen
 
-USAGE="Usage: $0 [-k] [file|unit|used|merge|mergeto|omitfrom|help] <file> [<file>]"
+USAGE="Usage: $0 [-I<dir>] [-G<dir>] [-u<uname>] [-k] [file|unit|used|merge|mergeto|omitfrom|help] [<file>] [<file>]"
 
 long_usage()
 {
     echo $USAGE
     echo 'Manage Gencot item property declarations in text format.'
     echo 'Commands:'
-    echo '  file     <cfile>   Create default property declarations for all items defined in C sourcefile <cfile>'
-    echo '  unit     <ufile>   Create default property declarations for all external items in unit described in <ufile>'
-    echo '  used     <ufile>   List external toplevel items used by unit described in <ufile>'
+    echo '  file     <cfile>  Create default property declarations for all items defined in C sourcefile <cfile>'
+    echo '  unit              Create default property declarations for all external items in unit'
+    echo '  used              List external toplevel items used by unit'
     echo '  merge    <file1> <file2> Merge two declarations by uniting properties for each item'
     echo '  mergeto  <file1> <file2> Merge properties from <file2> to items in <file1>'
     echo '  omitfrom <file1> <file2> Omit properties in <file2> from items in <file1>'
-    echo '  help             Display this help information'
+    echo '  help              Display this help information'
     echo '  (all commands write the resulting property declarations or item list to stdout)'
-    echo 'A <ufile> contains a list of <cfile> names, each on a separate line.'
     echo 'Options: '
-    echo '  -I<dir>  Directory for searching C include files. Can be repeated, as for cpp. '
-    echo '  -G<dir>  Directory for searching Gencot auxiliary files. Only one can be given, default is "."'
-    echo '  -k   Keep directory with intermediate files and display it at the end.'
+    echo '  -I<dir>    Directory for searching C include files. Can be repeated, as for cpp. '
+    echo '  -G<dir>    Directory for searching Gencot auxiliary files. Only one can be given, default is "."'
+    echo '  -u<uname>  Name of unit. Default is "all"'
+    echo '  -k         Keep directory with intermediate files and display it at the end.'
 }
 
 short_usage()
@@ -40,7 +40,7 @@ short_usage()
 }
 
 # Parse options
-OPTS=$(getopt -o hkI:G: -n "$0" -- "$@")
+OPTS=$(getopt -o hku:I:G: -n "$0" -- "$@")
 
 if [ $? != 0 ]
 then
@@ -53,6 +53,8 @@ eval set -- "$OPTS"
 INCLPATH=''
 GENCOTDIR='.'
 KEEP=''
+UNITNAME='all'
+
 add_incl()
 {
     if [ "$1" == "." ] 
@@ -71,6 +73,7 @@ while true; do
     case "$1" in
         -h) long_usage; exit;;
         -k) KEEP='yes'; shift;;
+        -u) shift; UNITNAME="$1"; shift;;
         -I) shift; add_incl "$1"; shift;;
         -G) shift; GENCOTDIR="$1"; shift;;
         --) shift; break;;
@@ -78,17 +81,17 @@ while true; do
 done
 
 # Parse command
-REQARGS=1
+REQARGS=2
 OPTARGS=''
 CMD=$1
 
 case "$CMD" in
-    file) ;;
-    unit) ;;
-    used) ;;
-    merge) REQARGS=2;;
-    mergeto) REQARGS=2;;
-    omitfrom) REQARGS=2;;
+    file) REQARGS=1;;
+    unit) REQARGS=0;;
+    used) REQARGS=0;;
+    merge) ;;
+    mergeto) ;;
+    omitfrom) ;;
     help) long_usage; exit;;
     *) echo "unknown items command: $1"; short_usage; exit;;
 esac
@@ -106,6 +109,24 @@ else
     if [ "$REQARGS" != "$#" ]
     then
         echo "wrong number of arguments for items command ${CMD}: expected $REQARGS"
+        exit
+    fi
+fi
+
+UNITFILE=$UNITNAME.unit
+
+if [ "$REQARGS" = "1" ]
+then
+    CFILE=$1
+    CBASE=$(basename $CFILE)
+    CNAME=$(expr match $CBASE '\(.*\)[.][^.]*' '|' $CBASE)
+elif [ "$REQARGS" = "0" ]
+then
+    if [ -e $GENCOTDIR/$UNITFILE ]
+    then 
+        echo "Using unit file $UNITFILE" >&2
+    else
+        echo "Error: Unit file $UNITFILE not found."
         exit
     fi
 fi
@@ -179,20 +200,14 @@ then
     $BIN/gencot-prclist < $1 | $PRC omit $TMPDIR/hfile
 elif [ "$CMD" == "file" ]
 then
-    CFILE=$1
-    CBASE=$(basename $CFILE)
-    CNAME=$(expr match $CBASE '\(.*\)[.][^.]*' '|' $CBASE)
     prepare_cfile $CFILE
     $GEN $CBASE < $TMPDIR/$CNAME.in
 elif [ "$CMD" == "unit" -o "$CMD" == "used" ]
 then
-    UFILE=$1
-    UBASE=$(basename $UFILE)
-    UNAME=$(expr match $UBASE '\(.*\)[.][^.]*' '|' $UBASE)
-    MIFILE=$GENCOTDIR/$UNAME.unit-manitems
-    PMIFILE=$TMPDIR/$UNAME.unit-prcman
+    MIFILE=$GENCOTDIR/$UNITFILE-manitems
+    PMIFILE=$TMPDIR/$UNITFILE-prcmanitems
     prepare_manitems $MIFILE $PMIFILE
-    for file in $(cat $1)
+    for file in $(cat $GENCOTDIR/$UNITFILE)
     do prepare_cfile $file
     done
     if [ "$CMD" == "unit" ]
diff --git a/bin/parmod b/bin/parmod
--- a/bin/parmod
+++ b/bin/parmod
@@ -19,7 +19,7 @@ long_usage()
     echo 'Commands:'
     echo '  file   <cfile> <uitems> Create parmod description for all functions defined in C sourcefile <cfile>'
     echo '  close  <cfile> <uitems> Create parmod description for all functions declared for C sourcefile <cfile>'
-    echo '  unit   <ufile> <json>  Select descriptions from <json> for externals in unit described in <ufile>'
+    echo '  unit   <json>   Select descriptions from <json> for externals in unit'
     echo '  show   <json>   Display information about parmod description'
     echo '  idlist <json>   List function identifiers of parmod descriptions'
     echo '  diff   <json1> <json2>  Compare parmod descriptions in <json1> and <json2>'
@@ -34,11 +34,11 @@ long_usage()
     echo '  (addto|mergin|replin modify the first argument)'
     echo '  (out writes two files <json>-itemprops and <json>-omitprops)'
     echo 'A <uitems> file contains a list of used external toplevel item ids, each on a separate line.'
-    echo 'A <ufile> contains a list of <cfile> names, each on a separate line.'
     echo 'Options for commands file|close|unit: '
-    echo '  -I<dir>  Directory for searching C include files. Can be repeated, as for cpp. '
-    echo '  -G<dir>  Directory for searching Gencot auxiliary files. Only one can be given, default is "."'
-    echo '  -k   Keep directory with intermediate files and display it at the end.'
+    echo '  -I<dir>    Directory for searching C include files. Can be repeated, as for cpp. '
+    echo '  -G<dir>    Directory for searching Gencot auxiliary files. Only one can be given, default is "."'
+    echo '  -u<uname>  Name of unit. Default is "all"'
+    echo '  -k         Keep directory with intermediate files and display it at the end.'
 }
 
 short_usage()
@@ -48,7 +48,7 @@ short_usage()
 }
 
 # Parse options
-OPTS=$(getopt -o hkI:G: -n "$0" -- "$@")
+OPTS=$(getopt -o hku:I:G: -n "$0" -- "$@")
 
 if [ $? != 0 ]
 then
@@ -61,6 +61,8 @@ eval set -- "$OPTS"
 INCLPATH=''
 GENCOTDIR='.'
 KEEP=''
+UNITNAME='all'
+
 add_incl()
 {
     if [ "$1" = "." ] 
@@ -79,6 +81,7 @@ while true; do
     case "$1" in
         -h) long_usage; exit;;
         -k) KEEP='yes'; shift;;
+        -u) shift; UNITNAME="$1"; shift;;
         -I) shift; add_incl "$1"; shift;;
         -G) shift; GENCOTDIR="$1"; shift;;
         --) shift; break;;
@@ -95,7 +98,7 @@ CMD=$1
 case "$CMD" in
     file) PARSE='yes';REQARGS=2;;
     close) PARSE='yes';CLOSE='close';REQARGS=2;;
-    unit) PARSE='yes';REQARGS=2;;
+    unit) PARSE='yes';;
     show) ;;
     idlist) ;;
     diff) REQARGS=2;;
@@ -125,6 +128,8 @@ else
         exit
     fi
 fi
+
+UNITFILE=$UNITNAME.unit
 
 prepare_aux()
 {
@@ -183,18 +188,22 @@ fi
 
 if [ "$CMD" = "unit" ]
 then
-    UFILE=$1
-    UBASE=$(basename $UFILE)
-    UNAME=$(expr match $UBASE '\(.*\)[.][^.]*' '|' $UBASE)
-    MIFILE=$GENCOTDIR/$UNAME.unit-manitems
-    PMIFILE=$TMPDIR/$UNAME.unit-prcman
+    if [ -e $GENCOTDIR/$UNITFILE ]
+    then 
+        echo "Using unit file $UNITFILE" >&2
+    else
+        echo "Error: Unit file $UNITFILE not found."
+        exit
+    fi
+    MIFILE=$GENCOTDIR/$UNITFILE-manitems
+    PMIFILE=$TMPDIR/$UNITFILE-prcmanitems
     prepare_manitems $MIFILE $PMIFILE
-    for file in $(cat $1)
+    for file in $(cat $GENCOTDIR/$UNITFILE)
     do prepare_cfile $file
     done
     $BIN/items-used $PMIFILE < $TMPDIR/infiles > $TMPDIR/useditems
     $BIN/items-extfuns $TMPDIR/useditems < $TMPDIR/infiles | sort > $TMPDIR/extfunids
-    $BIN/$PRC filter $TMPDIR/extfunids < $2 | tee $TMPDIR/extfuns.json \
+    $BIN/$PRC filter $TMPDIR/extfunids < $1 | tee $TMPDIR/extfuns.json \
         | $BIN/$PRC funids | sort | diff - $TMPDIR/extfunids > $TMPDIR/extfunids.diff
     if [ -s $TMPDIR/extfunids.diff ]
     then
