implement auxcog shallow

diff --git a/bin/auxcog b/bin/auxcog
--- a/bin/auxcog
+++ b/bin/auxcog
@@ -9,7 +9,7 @@ fi
 
 BIN=$GENCOT_HOME/bin
 
-USAGE="Usage: $0 [-I<dir>] [-u<unam>] [unit|comments|help] [<file>]"
+USAGE="Usage: $0 [-I<dir>] [-G<dir>] [-O<dir>] [-u<uname>] [-k] [unit|shallow|comments|help] [<file>]"
 
 long_usage()
 {
@@ -17,11 +17,15 @@ long_usage()
     echo 'Auxiliary processing for Cogent programs.'
     echo 'Commands:'
     echo '  unit             Generate auxiliary C files for unit described in <ufile>'
+    echo '  shallow <file>   Extend the shallow embedding generated by Cogent in <file>'
     echo '  comments <file>  Remove comments from Cogent source <file> and print to stdout'
     echo '  help             Display this help information'
-    echo 'Options for command unit: '
-    echo '  -I<dir>    Directory for searching Cogent include files. Can be repeated, as for cpp. '
+    echo 'Options for commands unit, shallow: '
+    echo '  -I<dir>    Directory for searching Cogent and C include files. Can be repeated, as for cpp. '
+    echo '  -G<dir>    Directory for searching Gencot auxiliary files. Only one can be given, default is "."'
+    echo '  -O<dir>    Directory for generated output files. Default is "."'
     echo '  -u<uname>  Name of unit. Default is "all"'
+    echo '  -k         Keep directory with intermediate files and display it at the end.'
 }
 
 short_usage()
@@ -31,7 +35,7 @@ short_usage()
 }
  
 # Parse options
-OPTS=$(getopt -o hu:I: -n "$0" -- "$@")
+OPTS=$(getopt -o hku:I:G:O: -n "$0" -- "$@")
 
 if [ $? != 0 ]
 then
@@ -42,12 +46,18 @@ fi
 eval set -- "$OPTS"
 
 INCLS=''
+GENCOTDIR='.'
+OUTPUTDIR='.'
+KEEP=''
 UNITNAME='all'
 
 while true; do
     case "$1" in
         -h) long_usage; exit;;
+        -k) KEEP='yes'; shift;;
         -I) shift; INCLS="$INCLS -I $1"; shift;;
+        -G) shift; GENCOTDIR="$1"; shift;;
+        -O) shift; OUTPUTDIR="$1"; shift;;
         -u) shift; UNITNAME="$1"; shift;;
         --) shift; break;;
     esac
@@ -60,6 +70,7 @@ CMD=$1
 
 case "$CMD" in
     unit) REQARGS=0;;
+    shallow) ;;
     comments) ;;
     help) long_usage; exit;;
     *) echo "unknown auxcog command: $1"; short_usage; exit;;
@@ -86,7 +97,7 @@ UNITFILE=$UNITNAME.unit
 
 if [ "$REQARGS" = "0" ]
 then
-    if [ -e $UNITFILE ]
+    if [ -e $GENCOTDIR/$UNITFILE ]
     then 
         echo "Using unit file $UNITFILE" >&2
     else
@@ -95,28 +106,86 @@ then
     fi
 fi
 
+if [ "$CMD" != "comments" ]
+then
+    TMPDIR=$(mktemp -d)
+fi
+
+if [ "$CMD" != "comments" ]
+then
+    if [ -e $UNITNAME-gen.h ]
+    then
+        cpp $INCLS < $UNITNAME-gen.h | $BIN/auxcog-ctypstruct > $TMPDIR/ctypstruct
+        cpp $INCLS < $UNITNAME-gen.h | $BIN/auxcog-ctypfunc > $TMPDIR/ctypfunc
+    else
+        echo "Error: file $UNITNAME-gen.h not found."
+    fi
+    if [ -e $GENCOTDIR/common.gencot-std ]
+    then 
+        cp $GENCOTDIR/common.gencot-std $TMPDIR
+    else
+        touch $TMPDIR/common.gencot-std
+    fi
+fi
+
 if [ "$CMD" = "unit" ]
 then
     if [ -e $UNITNAME-gencot_pp_inferred.c ]
     then
-        $BIN/auxcog-genops $UNITNAME-gen.h < $UNITNAME-gencot_pp_inferred.c > $UNITNAME-gencot.c
+        $BIN/auxcog-genops $TMPDIR/ctypstruct $TMPDIR/ctypfunc < $UNITNAME-gencot_pp_inferred.c > $OUTPUTDIR/$UNITNAME-gencot.c
     fi
-    $BIN/auxcog-genops $UNITNAME-gen.h < $UNITNAME-externs_pp_inferred.c > $UNITNAME-externs.c
-    for file in $(cat $UNITFILE)
+    $BIN/auxcog-genops $TMPDIR/ctypstruct $TMPDIR/ctypfunc < $UNITNAME-externs_pp_inferred.c > $OUTPUTDIR/$UNITNAME-externs.c
+    for file in $(cat $GENCOTDIR/$UNITFILE)
     do
         fbase=$(basename $file)
         fnam=$(expr match $fbase '\(.*\)[.][^.]*' '|' $fbase)
         if [ $fnam != "additional_externs" ]
-        then $BIN/auxcog-genops $UNITNAME-gen.h < $fnam-entry_pp_inferred.c > $fnam-entry.c
+        then $BIN/auxcog-genops $TMPDIR/ctypstruct $TMPDIR/ctypfunc < $fnam-entry_pp_inferred.c > $OUTPUTDIR/$fnam-entry.c
         fi
     done
     if [ -e $UNITNAME-manabstr_pp_inferred.c ]
     then
-        $BIN/auxcog-genops $UNITNAME-gen.h < $UNITNAME-manabstr_pp_inferred.c > $UNITNAME-manabstr.c
+        $BIN/auxcog-genops $TMPDIR/ctypstruct $TMPDIR/ctypfunc < $UNITNAME-manabstr_pp_inferred.c > $OUTPUTDIR/$UNITNAME-manabstr.c
     fi
+    KND=1
+    PRC=''
+    for comp in $(cat $TMPDIR/common.gencot-std)
+    do
+        if [ $KND ]
+        then
+            if [ $comp = "anti:" ]; then PRC=1; else PRC=''; fi
+            KND=''
+        else
+            if [ $PRC ]; then $BIN/auxcog-genops $TMPDIR/ctypstruct $TMPDIR/ctypfunc < std-${comp}_pp_inferred.c > $OUTPUTDIR/std-$comp.c; fi
+            KND=1
+        fi
+    done
     
-    $BIN/auxcog-mainfile $UNITNAME < $UNITFILE > $UNITNAME.c
+    $BIN/auxcog-mainfile $UNITNAME $TMPDIR/common.gencot-std < $GENCOTDIR/$UNITFILE > $OUTPUTDIR/$UNITNAME.c
+elif [ "$CMD" = "shallow" ]
+then
+    fbase=$(basename $1)
+    $BIN/auxcog-shallow $TMPDIR/ctypstruct < $1 > $OUTPUTDIR/$fbase
+    prfnam=$(expr match $fbase '\(.*\)_ShallowShared.thy')
+    srcdir=$(dirname $1)
+    cp $srcdir/${prfnam}_Shallow_Desugar.thy $OUTPUTDIR
+    echo "theory ShallowShared" > $OUTPUTDIR/ShallowShared.thy
+    echo "  imports \"${prfnam}_ShallowShared\"" >> $OUTPUTDIR/ShallowShared.thy
+    echo "begin end" >> $OUTPUTDIR/ShallowShared.thy
+    cp $GENCOT_HOME/isa/GencotTypes.thy $OUTPUTDIR
+    $BIN/auxcog-embedding $TMPDIR/common.gencot-std < $1 > $OUTPUTDIR/${prfnam}_Shallow_Embedding.thy
+    cp $GENCOT_HOME/isa/* $OUTPUTDIR
 else
 # "$CMD" = "comments"
     $BIN/auxcog-remcomments < $1
+fi
+
+if [ "$CMD" != "comments" ]
+then
+    if [ $KEEP ]
+    then
+        echo "Kept directory with intermediate files: $TMPDIR" >&2
+    else
+        rm -r $TMPDIR
+    fi
 fi
